name: Automatic infra deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature/AM-46-docker-deploy
    paths:
      - docker/**
      - .github/workflows/deploy-infra.yml

# GLOBAL ENVIRONMENT VARIABLES
env:
  OCI_TENANCY_NS: axkiihq3lcps
  OCI_REGISTRY: eu-paris-1.ocir.io
  OCI_REPOSITORY: grenadille/website
  OCI_GITHUB_USERNAME: ${{ secrets.OCI_GITHUB_USERNAME }}
  OCI_GITHUB_PASSWORD: ${{ secrets.OCI_GITHUB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to OCIR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.OCI_REGISTRY }}
          username: ${{ env.OCI_TENANCY_NS }}/${{ env.OCI_GITHUB_USERNAME }}
          password: ${{ env.OCI_GITHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: true
          tags: ${{ env.OCI_REGISTRY }}/${{ env.OCI_TENANCY_NS }}/${{ env.OCI_REPOSITORY }}:latest
